services:
  # Reverse proxy - Caddy
  caddy:
    image: caddy:2-alpine
    container_name: asigna-proxy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - asigna-network
  # Base de datos central
  # Catalogo de tenants y usuarios
  db-central:
    image: postgres:15-alpine
    container_name: asigna-central-db
    networks:
      - asigna-network
    env_file:
      - env/infra.env
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  # Cache y Gestion de sessiones
  redis:
    image: redis:7-alpine
    container_name: asigna-redis
    networks:
      - asigna-network
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  # Tenant-Middleware

networks:
  asigna-network:
    driver: bridge

